name: CI
on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop
    
env:
    UNITY_LICENSE: ${{secrets.UNITY_LICENSE}}
    
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        projectPath:
          - .
        unityVersion:
          - 2019.2.17f1
        targetPlatform:
          - StandaloneWindows64 # Build a Windows 64-bit standalone.
          - StandaloneOSX # Build a macOS standalone (Intel 64-bit).
          - StandaloneWindows # Build a Windows standalone.
          - StandaloneLinux64 # Build a Linux 64-bit standalone.
    steps:
        - name: Checkout Project
          uses: actions/checkout@v2
          with:
            lfs: true
        
        # Cache
        - name: Caching
          uses: actions/cache@v1.1.0
          with:
            path: ${{ matrix.projectPath }}/Library
            key: Library-${{ matrix.projectPath }}-${{ matrix.targetPlatform }}
            restore-keys: |
              Library-${{ matrix.projectPath }}-
              Library-
        
        # Build Windows
        - name: Unity - Builder
          uses: webbertakken/unity-builder@v1.1
          with:
            projectPath: ${{matrix.projectPath}}
            unityVersion: ${{matrix.unityVersion}}
            targetPlatform: ${{matrix.targetPlatform}}
         
        - name: Archive Build         
          uses: actions/upload-artifact@v1
          with:
            name: ${{matrix.targetPlatform}} build
            path: build/${{matrix.targetPlatform}}/      
            
